name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: Surgo/docker-smart-tag-action@v1
        id: smarttag
        with:
          docker_image: ""
          default_branch: main
          tag_with_sha: "true"
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: tsuru
      - env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          KO_DEFAULTBASEIMAGE: alpine:3.17.1
          TO_BUILD_TAG: ${{ steps.smarttag.outputs.tag }}
        run: |
          export TAGS=$(echo -n ':edge,:sha-34489bd7' | sed 's/://g')
          echo "Lets build tags: ${TAGS}"
          echo "${DOCKERHUB_PASSWORD}" | ko login docker.io --username ${DOCKERHUB_USERNAME} --password-stdin
          ko build -B --platform linux/arm64,linux/amd64 -t ${TAGS}
